/** Motion contracts displayed in the Docs tab. Source: design-system manifest and component map. */
export const motionSpecifications = {
  accordion: '## Анимация\n\nProgressive enhancement: измеренная panel-обёртка анимирует `height` от текущей к полной высоте за **400ms** по **cubic-bezier(0, 0, 0.06, 1)**, затем возвращается к `auto`. Декоративный Plus/Minus (stroke 2px) morph-ится вместе с `details[open]`; отдельные duration/easing не заданы. Hover меняет цвет title, meta и icon мгновенно. Без JavaScript остаётся нативный `details/summary` без анимации.',
  advantage: '## Анимация\n\nСобственной hover/focus-анимации нет. Только в Home все fact cards после **300ms** одновременно проходят `opacity: 0 → 1` и `translateY(-40px) → 0` за **600ms** по **cubic-bezier(0, 0, 0.06, 1)**. Это page-owned reveal и вне Home не применяется.',
  applicationForm: '## Анимация\n\nSuccess: без изменения layout `opacity: 0 → 1` и `translateY(8px) → 0`, **400ms**, **cubic-bezier(0.2, 0, 0, 1)**. Submitting не анимирует форму; loading Button использует три точки: цикл **1350ms**, **cubic-bezier(0.333, 0, 0.667, 1)**, opacity 1, `scale(1) → scale(1.5)`, подъём 2px, задержки **0 / 150 / 283.333ms**. Interactive story держит Submitting минимум **3000ms**.',
  badge: '## Анимация\n\nУ Badge нет утверждённой анимации, transition или интерактивного состояния. Метка статична; hover-эффекты и самостоятельная motion-логика запрещены.',
  button: '## Анимация\n\nPrimary меняет только opacity до 0.9, Secondary и Arrow — только фон: **200ms**, **cubic-bezier(0.2, 0, 0, 1)**. Active: opacity 0.8; disabled подавляет hover/active; Play не имеет hover-transition. Glyph Arrow прокручивается за **400ms** по **ease** (left: выход влево/вход справа, right — наоборот). Loading dots: **1350ms**, **cubic-bezier(0.333, 0, 0.667, 1)**, opacity 1, `scale(1) → scale(1.5)`, подъём 2px, задержки **0 / 150 / 283.333ms**.',
  dataTable: '## Анимация\n\nУ DataTable нет утверждённой component-owned animation или transition. Interactive row и доступная стрелка меняют нативные состояния без motion; pagination, empty state и mobile-представление также не имеют motion-контракта.',
  footer: '## Анимация\n\nГеометрия Footer не анимируется. У ссылок transition только `color` и `opacity`: **160ms** по **cubic-bezier(0.2, 0, 0, 1)**. Hover меняет цвет, active задаёт opacity 0.8, focus-visible — мгновенный outline. Других transforms, задержек или анимаций нет.',
  input: '## Анимация\n\nПри переходе default ↔ typing/filled label меняет размер и положение за **400ms** по **cubic-bezier(0.2, 0, 0, 1)**. Анимируется только label: высота поля 64px, layout и error copy не двигаются. Focus border, error, date/tel masks и disabled не имеют отдельной transition.',
  mediaCard: '## Анимация\n\nНа hover/focus-within только image/video preview масштабируется `scale(1) → scale(1.1)` в clipping container: **200ms**, **cubic-bezier(0, 0, 0.5, 1)**. Геометрия карточки и Play marker неподвижны. Duplicated title прокручивается вверх: **400ms**, **ease**, разделитель копий **4px**. Page-level reveal — отдельный контракт страницы.',
  newsCard: '## Анимация\n\nНа pointer hover карточка поднимается на **20px**: **400ms**, **cubic-bezier(0.46, 0, 0, 1)**; icon и title движутся вместе, нижний date Badge остаётся на месте. Hover/focus-within также прокручивают duplicated title вверх: **400ms**, **ease**, разделитель **4px**. Других свойств, задержек или layout-анимаций нет.',
  pageHero: '## Анимация\n\nС JavaScript title один раз при инициализации раскрывается из `opacity: 0; translateY(1.25rem)` в resting state: **400ms**, **cubic-bezier(0, 0, 0.18, 1)**, без задержки. Image и контейнер не анимируются; без JavaScript title сразу видим.',
  sidebar: '## Анимация\n\nВнешняя desktop-геометрия Sidebar не анимируется. На tablet меню — viewport-height overlay над следующим контентом: оно съезжает вниз за **400ms** по `easing-out`, затем navigation links переходят из `opacity: 0` в `1` за следующие **400ms**. Без JavaScript navigation, CTA и контакты сразу доступны. Navigation наследует TextLink/color: `color` **200ms**, **cubic-bezier(0.2, 0, 0, 1)**, без движения label. CTA наследует Button/Primary: opacity 0.9 за **200ms** по тому же easing, active 0.8. Focus-visible мгновенный.',
  teacherCard: '## Анимация\n\nПри hover полной карточки portrait в fixed clipping frame масштабируется `scale(1) → scale(1.1)`: **400ms**, **cubic-bezier(0.46, 0, 0, 1)**. Обе текстовые строки одновременно прокручиваются вверх: **400ms**, **ease**, разделитель копий **4px**. Размер карточки не меняется, задержки нет.',
  textLink: '## Анимация\n\nRoll прокручивает duplicated label вверх в clipped track: **400ms**, **ease**, без изменения layout. Color меняет secondary text на primary: **200ms**, **cubic-bezier(0.2, 0, 0, 1)**, без движения label. Color-inverse меняет только opacity до 0.9 за **200ms** по тому же easing. Active и focus-visible не имеют отдельной анимации.',
} as const;
