<?php
/** Teacher detail. @package Orlyata */
defined( 'ABSPATH' ) || exit;
$teacher_id = get_the_ID();
$teacher_about = get_page_by_path( 'o-kapelle' );
$teacher_back_url = $teacher_about instanceof WP_Post ? get_permalink( $teacher_about ) : home_url( '/o-kapelle/' );
$teacher_data = array(
'andrey-chernetsov'=>array('hero'=>'teachers-chernetsov.png','portrait'=>'vict.png','position'=>'Создатель и художественный руководитель капеллы. Руководитель младшего, старшего хора и юношеской группы, педагог по вокалу','rank'=>'Заслуженный работник культуры РФ','quote'=>'«Хоров девочек значительно больше, чем мальчиков. Многие родители считают, что мальчикам надо развивать тело и ум. А про воспитание души забывают. А это не менее важно! Музыка прекрасно воспитывает душу.\n\nИ мальчикам это необходимо не менее, чем девочкам. Мы стремимся научить петь всех, независимо от их музыкальных способностей. Пока не запоют мужчины, не запоёт страна!»','directory'=>'chernetsov'),
'irina-karpman'=>array('hero'=>'teachers/karpman.png','portrait'=>'karp.png','position'=>'Создатель капеллы и хормейстер младшего, старшего хора и юношеской группы, педагог по вокалу, теории музыки и сольфеджио.','rank'=>'Почётный работник культуры г. Москвы','quote'=>'«Давно доказано, что музыка и пение, в частности, оказывает положительное влияние на здоровье человека. Успокаивает, поднимает настроение, усиливает внимание, стимулирует интеллектуальную деятельность. Мы, педагоги капеллы, знаем и используем это в своей работе.

Дети, занимающиеся пением, могут привести в порядок лёгкие, улучшить кровообращение, исправить осанку, улучшить дикцию, устранить такой дефект, как заикание. Помогает при астме. Приходите к нам, и дети будут становиться здоровее и физически, и эмоционально!»','directory'=>'karpman','achievements'=>array(array('2026','Присвоено почетное звание «Почетный работник культуры города Москвы»: за заслуги в развитии культуры и многолетний добросовестный труд'),array('2015','Награждена дипломом «Лучший хормейстер» 5 Международного многожанрового фестиваля искусств «Фортуна» (г. Щелкино, Крым)'),array('2014','Лауреат Премии Правительства г. Москвы в номинации «За вклад в развитие культуры».'),array('2013','Дипломант XX Международного фестиваля-конкурса хорового искусства «Южная Пальмира» им. Александра Зайцева.'))),
'elena-chernetsova'=>array('hero'=>'teachers/chernetsova.png','portrait'=>'elena.png','position'=>'Хормейстер хора подготовительного отделения, педагог по вокалу, теории музыки и сольфеджио','quote'=>'«Петь в хоре — это счастье! Сочувствую тем людям, которые об этом не догадываются».','directory'=>'chernetsova','achievements'=>array(array('2024','Специальный диплом «За педагогическое мастерство» Московского международного фестиваля-конкурса «Рождественская песнь».'))),
'maryana-klimova'=>array('hero'=>'teachers/klimova.png','portrait'=>'mar.png','position'=>'Концертмейстер капеллы','quote'=>'«Капелла мальчиков и юношей «Орлята» — замечательное место для эстетического развития ребёнка. Здесь он может прикоснуться к прекрасному, познать настоящее мальчишеское братство, научиться общаться в коллективе, понять ответственность за общее дело и радость выступления на сцене!»','directory'=>'klimova','achievements'=>array(array('2023','Специальный диплом «За профессиональное мастерство» Климовой Марьяне Геннадиевне.'),array('2019','Лучший концертмейстер «Приношения Петру Чайковскому» 2019 г.'),array('2017','Лучший концертмейстер III хорового фестиваля-конкурса «Приношение Петру Чайковскому».'),array('2016','Лучший концертмейстер Московского открытого детско-юношеского фестиваля академического сольного пения «Посвящается Шаляпину».'))),
'olga-ugolnikova'=>array('hero'=>'teachers/ugolnikova.png','portrait'=>'olg.png','position'=>'Хормейстер младшего и старшего хора','directory'=>'ugolnikova'),
'mariya-moiseeva'=>array('hero'=>'teachers/moiseeva.png','portrait'=>'mash.png','position'=>'Хормейстер младшего и старшего хора','directory'=>'moiseeva'));
$teacher = $teacher_data[ get_post_field( 'post_name', $teacher_id ) ] ?? array();
$name = get_the_title( $teacher_id );
get_header(); ?>
<div class="orlyata-teacher-detail"><?php get_template_part( 'template-parts/layout/sidebar' ); ?><main class="orlyata-teacher-detail__content" id="main"><?php get_template_part( 'template-parts/components/page-hero', null, array('back_label'=>__( 'Вернуться на страницу «О капелле»','orlyata'),'back_url'=>$teacher_back_url,'corner_badge'=>$teacher['rank']??'','description'=>$teacher['position']??'','image_src'=>get_theme_file_uri('assets/images/news/bg-hero2.png'),'foreground_image_alt'=>$name,'foreground_image_src'=>get_theme_file_uri('assets/images/'.$teacher['hero']),'title'=>$name,'title_id'=>'teacher-detail-title','variant'=>'teacher-detail')); ?><div class="orlyata-teacher-detail__body">
<?php if(!empty($teacher['achievements'])): ?><section class="orlyata-teacher-detail__achievements" data-teacher-reveal><h2 class="type-heading-2">Достижения</h2><?php get_template_part('template-parts/components/data-table',null,array('headers'=>array('Год','Достижение'),'rows'=>$teacher['achievements'],'variant'=>'teacher-achievements')); ?></section><?php endif; ?>
<?php if(!empty($teacher['quote'])): ?><section class="orlyata-teacher-detail__quote" data-teacher-reveal><div class="orlyata-teacher-detail__quote-layout"><figure class="orlyata-teacher-detail__quote-portrait"><img src="<?php echo esc_url(get_theme_file_uri('assets/images/about/'.$teacher['portrait'])); ?>" alt="<?php echo esc_attr($name); ?>" width="240" height="240"></figure><blockquote class="orlyata-teacher-detail__quote-copy type-lead"><?php foreach(preg_split('/\R{2,}/',$teacher['quote']) as $paragraph): ?><p><?php echo esc_html($paragraph); ?></p><?php endforeach; ?></blockquote></div></section><?php endif; ?>
<?php get_template_part('template-parts/sections/teacher-gallery',null,array('directory'=>$teacher['directory'],'name'=>$name)); get_template_part('template-parts/layout/footer'); ?></div></main></div><?php get_footer();
